server:
  bindAddr: 0.0.0.0:8001  # string 用于提供http api的绑定地址

datastore:
  type: mongodb
  url: mongodb://dev:dev@localhost:27017 # string 数据库连接
  database: tv2okx # string 数据库名

okx:
  apiKey: <KEY> # string okx api key
  apiSecret: <KEY> # string okx api secret
  passphrase: <PASSWORD> # string okx api passphrase
